#!/usr/bin/env bash
# script that displays the PID, along with the process name, of processes whose name contain the word
for dir in /proc/[0-9]*; do [ -f "$dir"/comm ] && [ "$(cat "$dir"/comm)" == "bash" ] && echo "$(basename "$dir") $(cat "$dir"/comm)"; done
